# 행렬의 기본 연산

In [ ]:
import numpy as np

In [ ]:
ls1 = [1,2]
ls2 = [3,4]
ls3 = ls1 + ls2
print(ls3)

[1, 2, 3, 4]


In [1]:
s = 0
for i in range(10):
  s += i

assert s ==45,"s는 45여야 합니다." # assert 오류가 났는지 확인하기 위해 사용
# assert 조건, '메시지'로 사용

In [2]:
#ls 목록에 있는 요소의 합계를 구하는 함수
def calsum(ls):
  s = 0
  for e in ls:
    s+=e
  return s

In [3]:
assert calsum([1,2,3,2])==8,"calsum([1,2,3,2]) 값은 8이어야합니다."

In [4]:
def add(l1,l2):
  assert len(l1) == len(l2), "더하기 연산을 위해서는 요소의 길이가 같아야 합니다."
# assert : 원하는 대로 작동되지 않을 때 오류를 내게 하는것 
  re =[]
  for i in range(len(l1)):
    re.append(l1[i]+l2[i])
  return re

In [ ]:
ls1 = [1,2]
ls2 = [3,4]
ls3 = add(ls1, ls2)
print(ls3)

[4, 6]


In [ ]:
n1 = np.array([1,2]) #list보다 편하게 쓸 수 있다. numpy를 이용해서 
n2 = np.array([3,4])
n3 = n1 + n2
print(n3)

[4 6]


In [ ]:
n3 = n1 - n2
print(n3)

[-2 -2]


In [ ]:
ls1 = [1,2,3,4]
ls2 = ls1 *3
print(ls2)

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1*3
n3 = n1

In [ ]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
n1 = np.random.randint(1,1000,100,dtype=int)
# 1~1000 사이에 int 타입 100개 정수 무작위 추출
print(n1)

[976 944 312 884 599 231 918 129  72 653 767 275 120 912 571 402 491 629
 370 693 203 654 449 449  40 535 858  43 482 845 310 707 162 495  67  13
 388 186 556 543 326 101 528 142 734 393 995 311 204 655 178 258 236  19
 565 686 920 215 500 469 640 893 515 387 124 621 636 287 445 187 213 616
 522 731 974 567 885 611 242 934 790 635 420 566 696 250  98 642 839 875
 820 686 296 482 731  72 274 838 290 153]


In [ ]:
#500보다 큰 값 찾기
n2 = n1>500
print(n2)

[ True  True False  True  True False  True False False  True  True False
 False  True  True False False  True False  True False  True False False
 False  True  True False False  True False  True False False False False
 False False  True  True False False  True False  True False  True False
 False  True False False False False  True  True  True False False False
  True  True  True False False  True  True False False False False  True
  True  True  True  True  True  True False  True  True  True False  True
  True False False  True  True  True  True  True False False  True False
 False  True False False]


In [ ]:
# n2의 true의 값들만 리스트로출력
n3 = n1[n2]
print(n3)

[976 944 884 599 918 653 767 912 571 629 693 654 535 858 845 707 556 543
 528 734 995 655 565 686 920 640 893 515 621 636 616 522 731 974 567 885
 611 934 790 635 566 696 642 839 875 820 686 731 838]


In [ ]:
n1 = np.array([[1,2],[3,4]])
n2 = np.array([4,5])
n3 = np.dot(n1,n2) # 행렬의 내적함수 dot을 이용 곱하기.
print(n3)

[14 32]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1.reshape((2,2))
print(n2)

[[1 2]
 [3 4]]


In [ ]:
n3 = np.transpose(n2) #전치행렬: 행렬의 대각선을 기준으로 반대로 교차 시켜 출력하는 것
print(n3)

[[1 3]
 [2 4]]


In [ ]:
n3 = np.invert(n2) #invert: 반전(원소의 메모리)
print(n3)

[[-2 -3]
 [-4 -5]]


In [ ]:
n3 = np.linalg.inv(n2) #역행렬
print(n3)

In [ ]:
n4 = n2.dot(n3)
print(n4)

[[-10 -13]
 [-22 -29]]


In [ ]:
n1 = np.array([1,2,3,4])
n2 = n1-3
print(n2)

[-2 -1  0  1]


In [ ]:
n2 = n1/3
print(n2)

[0.33333333 0.66666667 1.         1.33333333]


# 통계관련

In [ ]:
n1 = np.random.randint(1,100,30,dtype = int)
print(n1)

[ 8 98 38  9 35 58 76 14 78 61 27 76 58 53  4 21 35  2 68 12 61 61  5 52
 46 41 50 93 43 29]


In [ ]:
print("길이: ",len(n1))

길이:  30


In [ ]:
print("평균: ", n1.mean())

평균:  43.733333333333334


In [ ]:
n2 = n1 -n1.mean()
print("수평 이동한 후 평균:", n2.mean())

수평 이동한 후 평균: -9.473903143468002e-16


In [ ]:
print("최대값 위치:",n1.argmax())
print("최대값:",n1[16])
print("최대값:",n1.max())


최대값 위치: 1
최대값: 35
최대값: 98


In [ ]:
print("분산:",n1.var())

분산: 703.9955555555555


In [ ]:
print("표준편차:",n1.std())

표준편차: 26.53291456955974


In [ ]:
n2 = n1/n1.std()
print("스케일 조절한 후 표준 편차:",n2.std())

스케일 조절한 후 표준 편차: 1.0


In [ ]:
print("최솟값: ",n1.min())
print("중앙값: ",np.median(n1))
print("1/4분위값: ",np.percentile(n1,0.25))
print("3/4분위값: ",np.percentile(n1,0.75))

최솟값:  2
중앙값:  44.5
1/4분위값:  2.145
3/4분위값:  2.435


In [ ]:
n1.sort()
print("누적 합:",np.cumsum(n1))

누적 합: [ 1  3  6 10 15 21 28 36 45]


In [ ]:
n1 = np.arange(1,10)
print(n1)
print("누적 곱:",np.cumprod(n1))

[1 2 3 4 5 6 7 8 9]
누적 곱: [     1      2      6     24    120    720   5040  40320 362880]
