<a href="https://colab.research.google.com/github/hyunjung930/Python/blob/hyunjung/%ED%86%B5%EA%B3%84%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D_%EC%A3%BC%EC%9A%94_%EB%AA%A8%EB%93%88_%EB%B3%B5%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 복습 P.133

장점 개요 - 행렬 계산이 편해졌다

In [2]:
ls = [1,2,3,4,5]
ls_twice = []
for e in ls:
  ls_twice.append(e*2)
ls_twice

[2, 4, 6, 8, 10]

In [18]:
import numpy as np
arr = np.array(ls)
arr_twice = arr*2
arr_twice

array([ 2,  4,  6, 16,  8])

In [19]:
arr = np.arange(10000)
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [17]:
arr = np.array(range(10000))
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

wrapping이란?

In [22]:
def madd(a,b):
  return a+b

In [23]:
def msum(ls):
  s = 0
  for e in ls:
    s = madd(s,e)
  return s

In [24]:
def count(ls):
  cnt = 0
  for _ in ls:
    cnt+=1
  return cnt

In [25]:
ls = [1,2,3,8,4]
s = msum(ls)
l = count(ls)
print(f'평균 : {s/l :.2f}')

평균 : 3.60


In [26]:
def average(ls):
  return msum(ls)

In [27]:
print(f'평균: {average(ls):.2f}') # 이미 만들어진 함수를 

평균: 18.00


#텐서


In [28]:
data = np.random.rand(5,2,3)
data

array([[[0.42086956, 0.81527406, 0.93160169],
        [0.89302299, 0.30593853, 0.0983934 ]],

       [[0.45006097, 0.0077597 , 0.43132143],
        [0.85122057, 0.21932564, 0.16311396]],

       [[0.0583691 , 0.93364962, 0.71346816],
        [0.49330805, 0.8733665 , 0.93834256]],

       [[0.41322095, 0.70956878, 0.42513303],
        [0.26433827, 0.63240553, 0.0175253 ]],

       [[0.61603012, 0.48454929, 0.21623589],
        [0.67080684, 0.18055326, 0.5406093 ]]])

In [29]:
data.shape

(5, 2, 3)

In [31]:
data2 = data.reshape(6,-1)
data2

array([[0.42086956, 0.81527406, 0.93160169, 0.89302299, 0.30593853],
       [0.0983934 , 0.45006097, 0.0077597 , 0.43132143, 0.85122057],
       [0.21932564, 0.16311396, 0.0583691 , 0.93364962, 0.71346816],
       [0.49330805, 0.8733665 , 0.93834256, 0.41322095, 0.70956878],
       [0.42513303, 0.26433827, 0.63240553, 0.0175253 , 0.61603012],
       [0.48454929, 0.21623589, 0.67080684, 0.18055326, 0.5406093 ]])

In [32]:
data2.shape

(6, 5)

In [ ]:
#data 3 = data.reshape(7,-1) #요구하는 구조로 정확하게 구성하지 못함
#data

In [33]:
#파이썬의 리스트는 tensor 자료가 아닐 수 있다.
zagged_arr = [[1,2,3],[1,2],[1,2,3,4,5]]
zagged_arr

[[1, 2, 3], [1, 2], [1, 2, 3, 4, 5]]

In [37]:
ls1 = [[1,2],[3,4]]
ls2 = [[4,6],[3,7]]
ls3 = ls1+ls2
ls3

[[1, 2], [3, 4], [4, 6], [3, 7]]

In [38]:
data2.ndim #ndim : 차원 알아보기

2

In [39]:
data2.shape

(6, 5)

#행렬계산

In [35]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[4,6],[3,7]])

arr3 = arr1+arr2
arr3

array([[ 5,  8],
       [ 6, 11]])

#원소 형식

In [40]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int64')

In [44]:
type(arr1[0])

numpy.ndarray

In [42]:
arr2 = np.array([1,2,3,4,5.])
arr2.dtype

dtype('float64')

In [45]:
type(arr2[0])

numpy.ndarray

In [46]:
arr3 = np.array([1,2,'a',4,5])
arr3.dtype

dtype('<U21')

In [47]:
type(arr3[0])

numpy.str_

In [48]:
arr3[0]

'1'

In [49]:
ls = [1,2,3,4,5.]
type(ls[0]),type(ls[4])

(int, float)

#형식변환


In [51]:
arr4 = np.array(['1','2','3','4'])
for e in arr4:
  print(e,end=',')
print()

1,2,3,4,


In [55]:
s =arr4[0]
for e in range(1,len(arr4)):
  s+=arr4[e]
print(s)

1234


In [57]:
arr5 = arr4.astype(int)
print(arr5.sum())

10


# 산술연산, 필터링

In [58]:
arr = np.array([[1,2],[3,4]])
sq_arr = arr*arr
sq_arr


array([[ 1,  4],
       [ 9, 16]])

In [59]:
d5_arr = arr/5
d5_arr

array([[0.2, 0.4],
       [0.6, 0.8]])

In [61]:
arr = np.array([-1,2,3,4,-4,9])
filter = arr>=0
print(filter)
darr = arr[filter]
print(darr)

[False  True  True  True False  True]
[2 3 4 9]


In [62]:
arr = np.array([[1,2,3],[4,5,6]])
arr.shape

(2, 3)

In [63]:
for i in range(2):
  for j in range(3):
    print(arr[i,j],end=',')
  print()

1,2,3,
4,5,6,


In [64]:
print(arr[0,1])
print(arr[0][1])

2
2


In [65]:
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [66]:
arr[3:10] #arr[3] ~ arr[10-1]

array([3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[:5]

array([0, 1, 2, 3, 4])

In [68]:
arr[95:]

array([95, 96, 97, 98, 99])

In [69]:
arr[-1]

99

In [70]:
arr[90:3]

array([], dtype=int64)

In [71]:
pre80 = arr[:len(arr)*4//5]
pre80

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [72]:
post20 = arr[len(arr)*4//5:]
post20

array([80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

# 필터링 강화

In [79]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
scores = np.array([90,80,74,90,78,88,85])
filter =names == 'Bob'
scores[filter]

array([90, 90])

In [80]:
texts = np.array(["Hello, How are you?","Where r u from?","RD GG","ready to go home"])
filter = [True if "r" in text else False for text in texts]
filter
texts[filter]

array(['Hello, How are you?', 'Where r u from?', 'ready to go home'],
      dtype='<U19')

numpy는 아니지만 컴프리핸션을 more...

In [82]:
data = [i*i for i in range(10)]
print(data)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [83]:
data2 = [i*i for i in range(10) if i%2==0]
print(data2)

[0, 4, 16, 36, 64]
